apiVersion: v1
kind: Service
metadata:
  name: cristopher-service
  namespace: cristopher-namespace
  labels:
    app: micro
spec:
  selector:
    app: micro
  ports:
  - port: 8088
    targetPort: 8087
    nodePort: 30088
    protocol: TCP
  type: LoadBalancer